CREATE DATABASE IF NOT EXISTS SITE_FORTES;
USE SITE_FORTES;

CREATE TABLE IF NOT EXISTS PROJETOS(
ID_PROJ INT PRIMARY KEY,
NOME_PROJ VARCHAR(45) NOT NULL,
ORCAMENTO DECIMAL(10,2) NOT NULL,
PUBLICO_ALVO VARCHAR(15) NOT NULL,
FINALIDADE VARCHAR(100) NOT NULL,
CATEGORIA VARCHAR(15) NOT NULL,
STATUS_AVALIACAO ENUM("PENDENTE","APROVADO","DESAPROVADO") NOT NULL
);

CREATE TABLE IF NOT EXISTS DOACOES(
ID_DOACAO INT PRIMARY KEY,
QUANTIA DECIMAL(10,2) NOT NULL,
DATA_DOACAO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS DOADORES(
ID_DOADOR INT PRIMARY KEY,
NOME_DOADOR VARCHAR(45),
EMAIL_DOA VARCHAR(45) NOT NULL,
TELEFONE VARCHAR(15),
CONSTRAINT DOACAOID FOREIGN KEY(ID_DOADOR) REFERENCES DOACAO(ID_DOACAO)
);

CREATE TABLE IF NOT EXISTS ADMINISTRADORES(
ID_ADM INT PRIMARY KEY,
NOME_ADM VARCHAR(45) NOT NULL,
EMAIL_ADM VARCHAR(45) NOT NULL,
TELEFONE_ADM VARCHAR(15) NOT NULL,
SENHA_ADM VARCHAR(45) NOT NULL,
CONSTRAINT PROJID FOREIGN KEY(ID_ADM) REFERENCES PROJETO(ID_PROJ)
);

CREATE TABLE IF NOT EXISTS INSTITUICOES(
CNPJ INT PRIMARY KEY,
NOME_INST VARCHAR(45) NOT NULL,
UF VARCHAR(45) NOT NULL,
CEP VARCHAR(45) NOT NULL,
LOGRADOURO VARCHAR(45) NOT NULL,
CIDADE VARCHAR(45) NOT NULL,
NUM_LOG INT NOT NULL,
BAIRRO VARCHAR(45) NOT NULL,
SENHA_INST VARCHAR(45) NOT NULL,
CONSTRAINT PROJCTID FOREIGN KEY(CNPJ) REFERENCES PROJETO(ID_PROJ)
);

CREATE TABLE IF NOT EXISTS PROJ_DOACAO(
COD_PROJ INT,
COD_DOA INT,
PRIMARY KEY(COD_PROJ,COD_DOA),
CONSTRAINT ID_ISN_DOA1 FOREIGN KEY(COD_PROJ) REFERENCES PROJETOS(ID_PROJ),
CONSTRAINT ID_ISN_DOA2  FOREIGN KEY(COD_DOA) REFERENCES DOACOES(ID_DOACAO)
);



